FROM tutum.co/lintci/ruby:2.2.3
MAINTAINER LintCI

ENV SENTRY_DSN="--CHANGEME--" \
    REDIS_URL="--CHANGEME--" \
    NEW_RELIC_APP_NAME="Push to Start" \
    NEW_RELIC_LICENSE_KEY="--CHANGEME--" \
    LOGENTRIES_TOKEN="--CHANGEME--" \
    SKYLIGHT_APPLICATION="--CHANGEME--" \
    SKYLIGHT_AUTHENTICATION="--CHANGEME--" \
    GITHUB_WEBHOOK_TOKEN="--CHANGEME--"
